tunnel: 9a532f8d-1f82-4998-8421-ea68a3313e08
credentials-file: C:\Users\Bruno\.cloudflared\9a532f8d-1f82-4998-8421-ea68a3313e08.json

ingress:
  - hostname: n8n-jurisconnect.jurisconnect.com.br
    service: http://127.0.0.1:5678
  # Route API traffic on same domain to bypass CORS
  - hostname: app.jurisconnect.com.br
    path: /api*
    service: http://127.0.0.1:3001
  - hostname: app.jurisconnect.com.br
    service: http://127.0.0.1:5173
  - hostname: api.jurisconnect.com.br
    service: http://127.0.0.1:3001
  - service: http_status:404
